branches:
  only:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_dd05710e44e2_key -iv $encrypted_dd05710e44e2_iv -in secring.gpg.enc -out secring.gpg -d
  - gpg --import secring.gpg

install:
  - ./gradlew uploadArchives